### PR TITLE
Utilize single config file for all scripts

### PR DESCRIPTION
**Pull request by watchmeexplode5**
Changes adopted from my prior work on the beta build. Scripts now reference a single config file. Also included addition of example files and another script to generate the config file automatically for ease of use on the end user. 

Goal with a single config file allows easier updates and less lines of code per script.

### CODE REVIEW

**Review by BinsonBuzz — APPROVED** [review]
Excellent - sorry it took so long

**Comment by mbryde** [comment]
If you wanted to use multiple remotes by utilizing an array of remotes etc ("remote-1","remote-2") - how would you parse that in the config file? I have sorte rewrote your commit, to utilize a single mounting file for multiple remotes. But I cannot use the config file. So I have to make sure both file have the same config lines in them.

**Comment by watchmeexplode5** [comment]
@MBryde,
Simplest way to mount multiple remotes would be to use multiple instances of the mounting script with a config for each  remote. IE: two config files like config_remote1, config_remote2. 

That being said, depending on your use case you might be better off editing the mount and config to include additional mount commands but that would be more effort.

**Comment by mbryde** [comment]
@watchmeexplode5 I already edited the mount script to support an array of remotes. But I would love to use the single config files. But parsing an array fuckes everything up

**Comment by watchmeexplode5** [comment]
I don't know what edits you have made but you should be able to add your extra variables into both the config and mount script. I haven't played around with parsing an array so you may have to figure that one out.

**Comment by jrdnlc** [comment]
Is this being merged anytime soon?

**Review by BinsonBuzz — APPROVED** [review]
Sorry it took so long

**Review by BinsonBuzz — APPROVED** [review]

**Comment by BinsonBuzz** [comment]
@watchmeexplode5  it won't let me add - it says there are conflicts that I can't resolve.  Any ideas?  Maybe a new commit?

**Review by BinsonBuzz — APPROVED** [review]

**Review by BinsonBuzz — APPROVED** [review]

**Comment by BinsonBuzz** [comment]
I've tried to merge a couple of times, but it's just not working.  Sorry to do this, but can you submit again please when you have time.

**Pull request closed without merging**
