### PR TITLE
Implemented Rclone GUI and config file

### PR DESCRIPTION
**Pull request by watchmeexplode5**
Lots of changes made. Most notably:

- **Addition of Rclone GUI**
- RC upload commands when gui enabled
- Uploads flagged and status polled to avoid rclone trying to double upload the same file
- Config Files for user variables (with config creator script for easy end user setup)
- Other useful scripts put in subfolder that some users might like
- GUI uses inclusion/exclusion text files - RC struggles with old exclusion methods (auto-created by upload script)

**If you want service accounts you need another independent service account remote**
 - Remotes are configured based on counter during each upload run. This is similar to the old way we used service accounts rotations (before adding it to the upload flags).
- Added examples for setup in the rclone.config file for reference.

Been running and modifying it for a while now. Hit stable state and been running fine for about a week. Just been tidying up and modifying little things since.

Still consider it a "beta" build since it has some pretty massive changes. I'd do an initial run on a test remote just encase (I never had any issues that would result in data loss and google will retain your deletes for 30 days so theoretically your safe).......... But I'd err on the safe side and it's probably best to setup a test remote and upload a handful of files just to make sure it's functioning as expected.

Also I'd steer clear of changing settings via the WebGUI. Lots of stuff works but it's not uncommon for settings to not stick. Quite a few parsing issues with regards to the webgui. No issue if you input wrong values though. Rclone will just ignore the gibberish settings it was fed. Scripts do fine with setting all the variables so no need to set them in the webgui anyway.

**Updated Readme should contain the majority of info about changes and setup.**

Feel free to add/change/scrap whatever. My feelings won't be hurt in the slightest if you don't like certain changes.

### CODE REVIEW

**Comment by watchmeexplode5** [comment]
Another note:

**Not sure if using WebGui will work with binding rclone to another ip**
- I can't test this.... my server crashes when I enable this in the scripts :/ I don't know why and it was never a function I utilized. 
- Currently the script disables binding if GUI is set (easy to remove the disable if you want to test - just remove the [bindmount=""] variable in the "if webgui=y statment"). I initially set it to disable when I thought it would cause issues but now that I'm rethinking it...... I don't actually think binding to a different ip would cause any issue. The mount script would also have to bind the ip BEFORE calling up a rclone gui instance so that would need to be re-ordered. 

Just an idea to explore for future improvement

**Review by BinsonBuzz — APPROVED** [review]
Can you do a pull request on the main script for just the config file changes i.e. leave out the rc stuff as I think it creates other challenges, whereas everyone will benefit from the config file changes.

**Comment by watchmeexplode5** [comment]
Yup, that's no problem. I'll add it to my to-do list

**Comment by BinsonBuzz** [comment]
Thanks.  I think the webgui is too early for the main thread, but I think
the way you've setup the config file will help people

**Pull request merged**
